// Curated sample movie data with real TMDB IDs so the app works seamlessly online & offline
const SAMPLE_MOVIES = {
  trending: [
    { id: 27205, title: "Inception", overview: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", poster_path: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg", vote_average: 8.4, release_date: "2010-07-16", media_type: "movie", genre_ids: [28, 878, 53] },
    { id: 155, title: "The Dark Knight", overview: "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest tests to fight injustice.", poster_path: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1FSNnH.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg", vote_average: 8.5, release_date: "2008-07-18", media_type: "movie", genre_ids: [28, 80, 18] },
    { id: 157336, title: "Interstellar", overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster_path: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/xJHokMbljXjADYdit5fK1B4FmyN.jpg", vote_average: 8.4, release_date: "2014-11-07", media_type: "movie", genre_ids: [12, 18, 878] },
    { id: 496243, title: "Parasite", overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", poster_path: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", vote_average: 8.5, release_date: "2019-05-30", media_type: "movie", genre_ids: [35, 53, 18] },
    { id: 693134, title: "Dune: Part Two", overview: "Paul Atreides unites with the Fremen to seek revenge against those who destroyed his family while trying to prevent a terrible future.", poster_path: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", vote_average: 8.2, release_date: "2024-02-27", media_type: "movie", genre_ids: [878, 12] },
    { id: 872585, title: "Oppenheimer", overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg", vote_average: 8.1, release_date: "2023-07-21", media_type: "movie", genre_ids: [18, 36] },
  ],
  action: [
    { id: 76341, title: "Mad Max: Fury Road", overview: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler with the aid of a drifter.", poster_path: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg", vote_average: 8.1, release_date: "2015-05-15", media_type: "movie", genre_ids: [28, 12, 878] },
    { id: 603692, title: "John Wick: Chapter 4", overview: "John Wick uncovers a path to defeating The High Table, but must face a new enemy with powerful alliances.", poster_path: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7BUY1p6f7Ymt.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg", vote_average: 7.8, release_date: "2023-03-24", media_type: "movie", genre_ids: [28, 53, 80] },
    { id: 361743, title: "Top Gun: Maverick", overview: "After thirty years of service, Pete Mitchell is called to train a group of Top Gun graduates for a specialized mission.", poster_path: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DG3hS1.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/AaV1YIdWKMzho5NJBNFYJMCd2aD.jpg", vote_average: 8.3, release_date: "2022-05-27", media_type: "movie", genre_ids: [28, 18] },
    { id: 414906, title: "The Batman", overview: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.", poster_path: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/5P8SmMzSNYikXpxil6BYzJ16611.jpg", vote_average: 7.7, release_date: "2022-03-04", media_type: "movie", genre_ids: [80, 28, 53] },
    { id: 575264, title: "Mission: Impossible – Dead Reckoning", overview: "Ethan Hunt and his IMF team must track down a terrifying new weapon before it falls into the wrong hands.", poster_path: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg", vote_average: 7.6, release_date: "2023-07-12", media_type: "movie", genre_ids: [28, 53] },
    { id: 569094, title: "Spider-Man: Across the Spider-Verse", overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People.", poster_path: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", vote_average: 8.4, release_date: "2023-06-02", media_type: "movie", genre_ids: [16, 28, 12] },
  ],
  comedy: [
    { id: 194662, title: "The Grand Budapest Hotel", overview: "A writer encounters the owner of an aging high-class hotel, who tells of his early years as lobby boy.", poster_path: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/nX5XotM9yprCKarRH4fzOq1VM1J.jpg", vote_average: 8.1, release_date: "2014-02-26", media_type: "movie", genre_ids: [35, 18] },
    { id: 667538, title: "Everything Everywhere All at Once", overview: "A middle-aged Chinese immigrant is swept up into an adventure where she alone can save existence.", poster_path: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/fBFv3e6IzLjMQ0QTst8FymAHR9G.jpg", vote_average: 8.0, release_date: "2022-03-25", media_type: "movie", genre_ids: [28, 35, 878] },
    { id: 546554, title: "Knives Out", overview: "A detective investigates the death of the patriarch of an eccentric, combative family.", poster_path: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg", vote_average: 7.9, release_date: "2019-11-27", media_type: "movie", genre_ids: [35, 80, 9648] },
    { id: 593643, title: "The Menu", overview: "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu.", poster_path: "https://image.tmdb.org/t/p/w500/v31MsWhF9WFh7Qpps10YVLfMGjf.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg", vote_average: 7.3, release_date: "2022-11-18", media_type: "movie", genre_ids: [35, 27, 53] },
    { id: 661374, title: "Glass Onion", overview: "Tech billionaire Miles Bron invites his friends for a getaway on his private island, but someone turns up dead.", poster_path: "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg", vote_average: 7.1, release_date: "2022-11-23", media_type: "movie", genre_ids: [35, 80, 9648] },
    { id: 346698, title: "Barbie", overview: "Barbie and Ken leave Barbieland and discover the joys and perils of living among humans.", poster_path: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/nHf61UzkfFno5dHhSax5EMJ3SnI.jpg", vote_average: 7.0, release_date: "2023-07-21", media_type: "movie", genre_ids: [35, 12, 14] },
  ],
  horror: [
    { id: 419430, title: "Get Out", overview: "A young African-American visits his white girlfriend's parents for the weekend, where his welcome begins to wear thin.", poster_path: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3zy7uCiqQhn1wnwb.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/lXCJSTJbRKJoa5VTVMUsFRVL2bS.jpg", vote_average: 7.6, release_date: "2017-02-24", media_type: "movie", genre_ids: [27, 53, 9648] },
    { id: 447332, title: "A Quiet Place", overview: "A family is forced to live in silence while hiding from creatures that hunt by sound.", poster_path: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/roYyPiQDQKmIKUEhO912jLdmfZM.jpg", vote_average: 7.4, release_date: "2018-04-06", media_type: "movie", genre_ids: [27, 18, 878] },
    { id: 493922, title: "Hereditary", overview: "A grieving family is haunted by tragic and disturbing occurrences after the death of their reclusive grandmother.", poster_path: "https://image.tmdb.org/t/p/w500/p9fmuz2Oj1JtMaDeIhb3mfCQSTm.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/5GbkL9DDRzq2fiZNeoYM0OHUaBT.jpg", vote_average: 7.3, release_date: "2018-06-08", media_type: "movie", genre_ids: [27, 18, 9648] },
    { id: 138843, title: "The Conjuring", overview: "Paranormal investigators work to help a family terrorized by a dark presence in their farmhouse.", poster_path: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/mnad1TmH9cqjB8MZpNGMXvCb4w1.jpg", vote_average: 7.5, release_date: "2013-07-19", media_type: "movie", genre_ids: [27, 53] },
    { id: 882598, title: "Smile", overview: "After witnessing a bizarre, traumatic incident, a therapist becomes increasingly convinced she is being threatened by an uncanny entity.", poster_path: "https://image.tmdb.org/t/p/w500/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg", vote_average: 6.8, release_date: "2022-09-30", media_type: "movie", genre_ids: [27, 53] },
    { id: 762504, title: "Nope", overview: "Residents of an isolated town witness an uncanny and chilling discovery.", poster_path: "https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/rCkwFzrIZDE1EAAG3R1YNFMniqk.jpg", vote_average: 7.0, release_date: "2022-07-22", media_type: "movie", genre_ids: [27, 878, 9648] },
  ],
  scifi: [
    { id: 335984, title: "Blade Runner 2049", overview: "A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.", poster_path: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg", vote_average: 7.5, release_date: "2017-10-06", media_type: "movie", genre_ids: [878, 18] },
    { id: 329865, title: "Arrival", overview: "A linguist works with the military to communicate with alien lifeforms after mysterious spacecraft land around the world.", poster_path: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/yIZ1xendyqKvY3FGeeUYUd5X9Mm.jpg", vote_average: 7.6, release_date: "2016-11-11", media_type: "movie", genre_ids: [878, 18, 9648] },
    { id: 603, title: "The Matrix", overview: "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.", poster_path: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg", vote_average: 8.2, release_date: "1999-03-31", media_type: "movie", genre_ids: [28, 878] },
    { id: 264660, title: "Ex Machina", overview: "A young programmer is selected to participate in a groundbreaking experiment in synthetic intelligence.", poster_path: "https://image.tmdb.org/t/p/w500/bvaxW9LJ1NOE0J8LMhE18uDvjk6.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/oOgmTSZfnEhBXDLA45hZs5yELsd.jpg", vote_average: 7.6, release_date: "2015-04-24", media_type: "movie", genre_ids: [878, 18, 53] },
    { id: 577922, title: "Tenet", overview: "Armed with only one word, a CIA operative journeys through a twilight world of international espionage.", poster_path: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/628Dep6AxEtDxjZoGP78TsOxYbK.jpg", vote_average: 7.2, release_date: "2020-08-26", media_type: "movie", genre_ids: [28, 53, 878] },
    { id: 300668, title: "Annihilation", overview: "A biologist signs up for a dangerous, secret expedition into a mysterious zone where nature has mutated.", poster_path: "https://image.tmdb.org/t/p/w500/d3c4VnIBJ9cGWmjEEaEBPn0JHXV.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/xHMo5Wtwv9yICc7TH9aJINcZfHD.jpg", vote_average: 6.8, release_date: "2018-02-23", media_type: "movie", genre_ids: [878, 27, 53] },
  ],
  tvPopular: [
    { id: 1396, title: "Breaking Bad", name: "Breaking Bad", overview: "A chemistry teacher diagnosed with terminal lung cancer turns to manufacturing methamphetamine.", poster_path: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", vote_average: 8.9, first_air_date: "2008-01-20", media_type: "tv", genre_ids: [18, 53] },
    { id: 66732, title: "Stranger Things", name: "Stranger Things", overview: "When a young boy disappears, his mother and friends must confront terrifying supernatural forces.", poster_path: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/56v2KjBlYj6mAoJ4MKqaezrvBeU.jpg", vote_average: 8.6, first_air_date: "2016-07-15", media_type: "tv", genre_ids: [18, 878, 9648] },
    { id: 100088, title: "The Last of Us", name: "The Last of Us", overview: "Joel and Ellie must survive in a post-apocalyptic world ravaged by a fungal pandemic.", poster_path: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg", vote_average: 8.8, first_air_date: "2023-01-15", media_type: "tv", genre_ids: [18, 878] },
    { id: 119051, title: "Wednesday", name: "Wednesday", overview: "Wednesday Addams is sent to Nevermore Academy where she attempts to master her emerging psychic ability.", poster_path: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/iHSwvRVsNBELLRK7iPArolDIH1F.jpg", vote_average: 8.5, first_air_date: "2022-11-23", media_type: "tv", genre_ids: [35, 80, 9648] },
    { id: 93405, title: "Squid Game", name: "Squid Game", overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.", poster_path: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/oaGvjB0DvdhXhOAuADfHb261ZHa.jpg", vote_average: 7.8, first_air_date: "2021-09-17", media_type: "tv", genre_ids: [18, 9648, 28] },
    { id: 94997, title: "House of the Dragon", name: "House of the Dragon", overview: "The story of the Targaryen civil war that took place about 200 years before Game of Thrones.", poster_path: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg", vote_average: 8.4, first_air_date: "2022-08-21", media_type: "tv", genre_ids: [18, 14, 28] },
  ],
  topRated: [
    { id: 278, title: "The Shawshank Redemption", overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", poster_path: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg", vote_average: 8.7, release_date: "1994-09-23", media_type: "movie", genre_ids: [18, 80] },
    { id: 238, title: "The Godfather", overview: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.", poster_path: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", vote_average: 8.7, release_date: "1972-03-14", media_type: "movie", genre_ids: [18, 80] },
    { id: 424, title: "Schindler's List", overview: "In German-occupied Poland, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.", poster_path: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/loRmRzQXZdqC7bfCmm7AXJEYQ7Z.jpg", vote_average: 8.6, release_date: "1993-11-30", media_type: "movie", genre_ids: [18, 36, 10752] },
    { id: 680, title: "Pulp Fiction", overview: "The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in four tales of violence and redemption.", poster_path: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", vote_average: 8.5, release_date: "1994-09-10", media_type: "movie", genre_ids: [53, 80] },
    { id: 550, title: "Fight Club", overview: "An insomniac office worker forms an underground fight club that evolves into something much more.", poster_path: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg", vote_average: 8.4, release_date: "1999-10-15", media_type: "movie", genre_ids: [18, 53] },
    { id: 13, title: "Forrest Gump", overview: "The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an IQ of 75.", poster_path: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", backdrop_path: "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg", vote_average: 8.5, release_date: "1994-06-23", media_type: "movie", genre_ids: [35, 18, 10749] },
  ]
};

export function getSampleData(category) {
  return { results: SAMPLE_MOVIES[category] || SAMPLE_MOVIES.trending };
}

export function getSampleDetails(id) {
  const all = Object.values(SAMPLE_MOVIES).flat();
  const movie = all.find(m => m.id === id);
  if (!movie) return null;
  return {
    ...movie,
    genres: (movie.genre_ids || []).map(gid => {
      const names = { 28:'Action',12:'Adventure',16:'Animation',35:'Comedy',80:'Crime',99:'Documentary',18:'Drama',10751:'Family',14:'Fantasy',36:'History',27:'Horror',10402:'Music',9648:'Mystery',10749:'Romance',878:'Sci-Fi',53:'Thriller',10752:'War',37:'Western' };
      return { id: gid, name: names[gid] || 'Unknown' };
    }),
    credits: { cast: [{ name: 'Sample Cast' }] },
    videos: { results: [] },
    similar: { results: SAMPLE_MOVIES.trending.filter(m => m.id !== id).slice(0, 4) },
    recommendations: { results: [] }
  };
}

export function hasTMDBKey() {
  return true; // Default key is hardcoded in tmdb.js
}
